<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<PlatformTarget>x64</PlatformTarget>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<UseWPF>true</UseWPF>
		<StartAction>Program</StartAction>
		<StartProgram>$(ProgramFiles)\Trados\Trados Studio\Studio19Beta\SDLTradosStudio.exe</StartProgram>
		<PluginDeploymentPath>$(AppData)\Trados\Trados Studio\19Beta\Plugins</PluginDeploymentPath>
		<CreatePluginPackage>true</CreatePluginPackage>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Resources\LocalyzerConnect_Icon.ico" />
	</ItemGroup>

	<ItemGroup>
		<!-- Embedded resources -->
		<EmbeddedResource Include="Resources\LocalyzerConnect_Icon.png" />
		<EmbeddedResource Include="Resources\getLocalyzer.html" />
		<EmbeddedResource Include="Resources\lingoport.svg" />
	</ItemGroup>

	<ItemGroup>
		<!-- Trados Studio API references -->
		<Reference Include="Sdl.Desktop.IntegrationApi">
			<HintPath>$(ProgramFiles)\Trados\Trados Studio\Studio19Beta\Sdl.Desktop.IntegrationApi.dll</HintPath>
		</Reference>
		<Reference Include="Sdl.Desktop.IntegrationApi.Extensions">
			<HintPath>$(ProgramFiles)\Trados\Trados Studio\Studio19Beta\Sdl.Desktop.IntegrationApi.Extensions.dll</HintPath>
		</Reference>
		<Reference Include="Sdl.Desktop.Platform">
			<HintPath>$(ProgramFiles)\Trados\Trados Studio\Studio19Beta\Sdl.Desktop.Platform.dll</HintPath>
		</Reference>
		<Reference Include="Sdl.FileTypeSupport.Framework.Core">
			<HintPath>$(ProgramFiles)\Trados\Trados Studio\Studio19Beta\Sdl.FileTypeSupport.Framework.Core.dll</HintPath>
		</Reference>
		<Reference Include="Sdl.FileTypeSupport.Framework.Implementation">
			<HintPath>$(ProgramFiles)\Trados\Trados Studio\Studio19Beta\Sdl.FileTypeSupport.Framework.Implementation.dll</HintPath>
		</Reference>
		<Reference Include="Sdl.ProjectAutomation.Core">
			<HintPath>$(ProgramFiles)\Trados\Trados Studio\Studio19Beta\Sdl.ProjectAutomation.Core.dll</HintPath>
		</Reference>
		<Reference Include="Sdl.ProjectAutomation.FileBased">
			<HintPath>$(ProgramFiles)\Trados\Trados Studio\Studio19Beta\Sdl.ProjectAutomation.FileBased.dll</HintPath>
		</Reference>
		<Reference Include="Sdl.ProjectAutomation.Settings">
			<HintPath>$(ProgramFiles)\Trados\Trados Studio\Studio19Beta\Sdl.ProjectAutomation.Settings.dll</HintPath>
		</Reference>
		<Reference Include="Sdl.TranslationStudio.Editor">
			<HintPath>$(ProgramFiles)\Trados\Trados Studio\Studio19Beta\Sdl.TranslationStudio.Editor.dll</HintPath>
		</Reference>
		<Reference Include="Sdl.TranslationStudioAutomation.IntegrationApi">
			<HintPath>$(ProgramFiles)\Trados\Trados Studio\Studio19Beta\Sdl.TranslationStudioAutomation.IntegrationApi.dll</HintPath>
		</Reference>
		<Reference Include="Sdl.TranslationStudioAutomation.IntegrationApi.Extensions">
			<HintPath>$(ProgramFiles)\Trados\Trados Studio\Studio19Beta\Sdl.TranslationStudioAutomation.IntegrationApi.Extensions.dll</HintPath>
		</Reference>
		<Reference Include="System" />
		<Reference Include="System.Core" />
		<Reference Include="System.Drawing" />
		<Reference Include="System.Windows.Forms" />
	</ItemGroup>

	<ItemGroup>
		<None Include="pluginpackage.manifest.xml" />
		<None Include="Properties\AssemblyInfo.cs" />
		<None Include="Properties\PluginProperties.cs" />
	</ItemGroup>

	<ItemGroup>
		<!-- NuGet packages -->
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2792.45">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="Sdl.Core.PluginFramework" Version="2.1.0" />
		<PackageReference Include="Sdl.Core.PluginFramework.Build" Version="18.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\LocalyzerConnect_Icon.ico" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="PluginResources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>PluginResources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="PluginResources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>PluginResources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>
